<?php

namespace NTI\TicketBundle\Repository\Ticket;

/**
 * TicketResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketResourceRepository extends \Doctrine\ORM\EntityRepository
{
}
