<?php

namespace NTI\TicketBundle\Repository\Board;

/**
 * BoardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoardRepository extends \Doctrine\ORM\EntityRepository
{
}
